import { BackgroundColorProvider } from '@/context/BackgroundColorContext';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Poppins, Press_Start_2P } from 'next/font/google';

import Providers from './providers';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

const pressStart2P = Press_Start_2P({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-press-start-2p',
  weight: ['400']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pressStart2P.variable} ${poppins.variable} antialiased`}
      >
        <BackgroundColorProvider>
          <Providers>{children}</Providers>
        </BackgroundColorProvider>
      </body>
    </html>
  );
}
